---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      securityContext:
         runAsUser: 1000
         runAsGroup: 3000
         fsGroup: 2000
         fsGroupChangePolicy: "OnRootMismatch"
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hello-flask
          image: {{ .Values.image }}
          securityContext:
            readOnlyRootFilesystem: true
          command:
            - /app/app.py
            - {{ .Values.greeting }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: metrics
