---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-helm
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
    - host: {{ .Values.hostname }}.codemowers.ee
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hello-flask
                port:
                  number: 8000
  tls:
    - hosts:
        - "*.codemowers.ee"
